export {
  APP_NAV,
  APP_NAV_GROUPS,
  canAccessPath,
  canEditResource,
  canViewResource,
  defaultHomeForRole,
  isSuperAdmin,
  navGroupsForRole,
  navItemsForRole,
  resourceForPath,
  type NavGroup,
  type NavItem,
  type PermissionMap,
} from '@/lib/permissions';
