export const DEFAULT_TEXTS: Record<string, string> = {
  // Devices
  'devices.title': 'Devices',
  'devices.description': 'Lista uređaja. Pretraga po serijskom broju, nazivu, kompaniji ili distributeru.',
  'devices.btn.exportCsv': 'Export CSV',
  'devices.btn.import': 'Import',
  'devices.btn.addNew': 'Dodaj novi uređaj',
  'devices.btn.clearFilter': 'Poništi filter',
  'devices.input.search.placeholder': 'Pretraži…',
  'devices.select.distributor.all': 'Svi distributeri',
  'devices.th.name': 'Name',
  'devices.th.model': 'Model',
  'devices.th.serial': 'Serial',
  'devices.th.company': 'Company',
  'devices.th.distributor': 'Distributer',
  'devices.th.subDistributor': 'Pod-distributer',
  'devices.th.status': 'Status',
  'devices.th.updated': 'Updated',
  'devices.th.actions': 'Actions',
  'devices.empty': 'No devices found.',

  // Distributors
  'distributors.title': 'Distributeri',
  'distributors.description':
    'Lista distributera iz Teron uvoza i ručnog dodeljivanja na uređajima. Klik na distributera filtrira uređaje.',
  'distributors.input.search.placeholder': 'Pretraži distributere…',
  'distributors.th.name': 'Naziv',
  'distributors.th.count': 'Broj uređaja',
  'distributors.th.actions': 'Akcije',
  'distributors.action.devices': 'Uređaji',
  'distributors.loading': 'Učitavanje…',
  'distributors.error': 'Učitavanje distributera nije uspelo.',
  'distributors.empty.noDistributors': 'Nema distributera. Uvezi Teron Excel na stranici Uređaji.',
  'distributors.empty.noResults': 'Nema rezultata pretrage.',

  // Sub-distributors
  'subDistributors.title': 'Pod-distributeri',
  'subDistributors.description':
    'Pod-distributeri su distributeri čiji naziv sadrži /. Glavni distributer je naziv pre /.',
  'subDistributors.input.search.placeholder': 'Pretraži pod-distributere…',
  'subDistributors.action.openDistributors': 'Otvori distributere',
  'subDistributors.th.name': 'Naziv',
  'subDistributors.th.count': 'Broj uređaja',
  'subDistributors.th.actions': 'Akcije',
  'subDistributors.action.devices': 'Uređaji',
  'subDistributors.loading': 'Učitavanje…',
  'subDistributors.error': 'Učitavanje pod-distributera nije uspelo.',
  'subDistributors.empty': 'Nema pod-distributera.',
  'subDistributors.empty.noResults': 'Nema rezultata pretrage.',

  // Tickets (non-error strings only; error messages intentionally excluded)
  'tickets.title': 'Tickets',
  'tickets.btn.create': 'Create Ticket',
  'tickets.input.search.placeholder': 'Pretraži tikete (key, naslov, korisnik)…',
  'tickets.filter.status': 'Status',
  'tickets.filter.type': 'Type',
  'tickets.filter.assignee': 'Assignee',
  'tickets.filter.createdBy': 'Created by',
  'tickets.filter.company': 'Company',
  'tickets.filter.created': 'Created',
  'tickets.table.key': 'Key',
  'tickets.table.title': 'Title',
  'tickets.table.status': 'Status',
  'tickets.table.type': 'Type',
  'tickets.table.company': 'Company',
  'tickets.table.contactMethod': 'Način kontakta',
  'tickets.table.contactsContactedCount': 'Broj kontakt.',
  'tickets.table.assignee': 'Assignee',
  'tickets.table.createdBy': 'Created by',
  'tickets.table.createdAt': 'Created',
  'tickets.table.updatedAt': 'Updated',
  'tickets.table.actions': 'Akcije',
  'tickets.pagination.prev': 'Previous',
  'tickets.pagination.next': 'Next',
  'tickets.btn.edit': 'Edit',
  'tickets.btn.delete': 'Obriši',

  // Licences
  'licences.title': 'Licences',
  'licences.description': 'Pregled licenci. Filtriraj po statusu (ACTIVE/EXPIRED…).',
  'licences.btn.exportCsv': 'Export CSV',
  'licences.btn.import': 'Import',
  'licences.btn.addNew': 'Add new Licence',
  'licences.btn.clear': 'Clear',
  'licences.filter.status': 'Status',
  'licences.filter.company': 'Company',
  'licences.filter.expiring': 'Expiring',
  'licences.th.product': 'Product',
  'licences.th.company': 'Company',
  'licences.th.device': 'Device',
  'licences.th.status': 'Status',
  'licences.th.validTo': 'Valid to',
  'licences.th.updated': 'Updated',
  'licences.th.actions': 'Actions',

  // Projects / Work log
  'projects.title': 'Evidencija rada po projektima',
  'projects.description': 'Pregled projekata i evidencija utrošenog vremena.',
  'projects.btn.create': 'Napravi Projekat',
  'projects.btn.create.confirm': 'Napravi',
  'projects.btn.edit': 'Edit',
  'projects.btn.delete': 'Delete',
  'projects.btn.cancel': 'Odustani',
  'projects.btn.save': 'Sačuvaj',
  'projects.btn.saving': 'Čuvanje…',
  'projects.loading': 'Učitavanje…',
  'projects.error': 'Učitavanje projekata nije uspelo.',
  'projects.empty': 'Nema projekata.',
  'projects.th.name': 'Projekat',
  'projects.th.startDate': 'Početak',
  'projects.th.endDate': 'Kraj',
  'projects.th.assignees': 'Dodeljeni',
  'projects.th.company': 'Kompanija',
  'projects.th.distributor': 'Distributer',
  'projects.th.actions': 'Akcije',
  'projects.modal.create.title': 'Napravi projekat',
  'projects.modal.edit.title': 'Izmeni projekat',
  'projects.form.name': 'Naziv projekta',
  'projects.form.name.placeholder': 'Unesi naziv…',
  'projects.form.startDate': 'Datum početka',
  'projects.form.endDate': 'Datum kraja (opciono)',
  'projects.form.endDate.hint': 'Ostavi prazno ako projekat nema definisan kraj.',
  'projects.form.assignees': 'Osobe dodeljene na projektu',
  'projects.form.company': 'Kompanija (klijent)',
  'projects.form.company.placeholder': 'Pretraži kompaniju po nazivu…',
  'projects.form.distributor': 'Distributer',
  'projects.form.distributor.placeholder': 'Pretraži distributera po nazivu…',

  'projectDetail.title': 'Projekat',
  'projectDetail.btn.back': '<--- Nazad',
  'projectDetail.btn.createWorkOrder': 'Kreiraj radni nalog na projektu',
  'projectDetail.btn.exportExcel': 'Export Excel',
  'projectDetail.btn.exporting': 'Export…',
  'projectDetail.totalHours': 'Ukupno utrošeno (sati)',
  'projectDetail.hoursByUser': 'Utrošeno po korisniku (sati)',
  'projectDetail.hoursByUser.empty': 'Nema unetih radnih naloga.',
  'projectDetail.meta': 'Detalji:',
  'projectDetail.meta.start': 'Početak',
  'projectDetail.meta.end': 'Kraj',
  'projectDetail.meta.assignees': 'Dodeljeni',

  'workOrders.loading': 'Učitavanje…',
  'workOrders.empty': 'Nema radnih naloga.',
  'workOrders.th.date': 'Datum',
  'workOrders.th.title': 'Radni nalog',
  'workOrders.th.type': 'Tip',
  'workOrders.th.contract': 'Ugovor',
  'workOrders.th.user': 'Serviser',
  'workOrders.th.hours': 'Sati',
  'workOrders.th.actions': 'Akcije',
  'workOrders.btn.edit': 'Edit',
  'workOrders.btn.delete': 'Delete',
  'workOrders.btn.cancel': 'Odustani',
  'workOrders.btn.save': 'Sačuvaj',
  'workOrders.btn.saving': 'Čuvanje…',
  'workOrders.btn.today': 'Trenutni datum',
  'workOrders.btn.create.confirm': 'Kreiraj',
  'workOrders.btn.addLine': '+ Dodaj artikal',
  'workOrders.btn.removeLine': 'Ukloni',
  'workOrders.modal.create.title': 'Kreiraj radni nalog',
  'workOrders.modal.edit.title': 'Izmeni radni nalog',
  'workOrders.form.title': 'Naziv radnog naloga',
  'workOrders.form.title.placeholder': 'Unesi naziv…',
  'workOrders.form.type': 'Tip',
  'workOrders.form.type.reklamacija': 'Reklamacija',
  'workOrders.form.type.implementacija': 'Implementacija',
  'workOrders.form.contractNumber': 'Broj ugovora (serijski broj)',
  'workOrders.form.contractNumber.placeholder': 'npr. Kartomati - Ugovor 1/20',
  'workOrders.form.requestedWork': 'Zahtevani radovi',
  'workOrders.form.requestedWork.placeholder': 'Unesi zahtevane radove…',
  'workOrders.form.performedWork': 'Izvršeni radovi',
  'workOrders.form.performedWork.placeholder': 'Unesi izvršene radove…',
  'workOrders.form.hours': 'Ukupno sati (zbir količina)',
  'workOrders.form.hours.hint': 'Računa se automatski iz stavki artikala',
  'workOrders.form.date': 'Datum',
  'workOrders.form.date.placeholder': 'dd/mm/yyyy ili yyyy-mm-dd',
  'workOrders.form.date.hint': 'Podržano: dd/mm/yyyy, dd.mm.yyyy, dd-mm-yyyy ili ISO (yyyy-mm-dd).',
  'workOrders.form.lines': 'Artikli',
  'workOrders.form.lines.code': 'Kod / Proizvod',
  'workOrders.form.lines.quantity': 'Količina',
  'workOrders.form.lines.unit': 'JM',
  'workOrders.form.lines.price': 'Cena',
  'workOrders.form.lines.priceVat': 'Cena + PDV',
  'workOrders.form.lines.select': 'Izaberi artikal…',
  'workOrders.form.lines.max': 'Maksimalno 2 artikla (po jedan od svakog koda).',
  'licences.btn.edit': 'Edit',

  // Clients
  'clients.title': 'Korisnici',
  'clients.description': 'Korisnici (kompanije) i kontakti.',
  'clients.tab.users': 'Korisnici',
  'clients.tab.contacts': 'Kontakti',
  'clients.btn.addUser': 'Dodaj korisnika',
  'clients.btn.addContact': 'Dodaj kontakt',
  'clients.users.search.placeholder': 'Pretraži korisnike (naziv, grad, PIB, MB)…',

  // Sales
  'sales.title': 'Prodaja',
  'sales.tab.calls': 'Pozivi',
  'sales.tab.directory': 'Mailovi i pozivi',
  'sales.tab.distributorEmails': 'Mailovi distributerima',

  // Reports
  'reports.title': 'Reports',
  'reports.generator.title': 'Generator izveštaja',

  // Leave
  'leave.title': 'Odsustva',
  'leave.btn.request': 'Zahtev za odsustvo',
  'leave.scope.company': 'Kompanija',
  'leave.scope.my': 'Moji',
  'leave.view.timeline': 'Timeline',
  'leave.view.calendar': 'Kalendar',
  'leave.type.annual': 'Godišnji odmor',
  'leave.type.paid': 'Plaćeno odsustvo',
  'leave.type.personal': 'Slobodni dani',
  'leave.banner.unused': 'Imate neiskorišćen godišnji odmor — iskoristite do 30.06.',

  // Settings
  'settings.title': 'Settings',
  'settings.texts.title': 'Text Management',
  'settings.texts.description':
    'Uredi tekstove na sajtu. Promene se vide posle reload stranice.',
  'settings.texts.btn.save': 'Sačuvaj promene',
  'settings.texts.btn.saving': 'Čuvam…',
  'settings.texts.btn.reset': 'Reset',
  'settings.texts.loading': 'Loading…',
  'settings.texts.error': 'Ne mogu da učitam tekstove. Proveri backend.',
  'settings.texts.group.nav': 'Navigacija',
  'settings.texts.group.shell': 'Okvir aplikacije',
  'settings.texts.group.common': 'Opšte',
  'settings.texts.group.dashboard': 'Dashboard',
  'settings.texts.group.todo': 'TO DO',
  'settings.texts.group.settings': 'Settings',
  'settings.texts.group.reports': 'Reports',
  'settings.texts.group.devices': 'Uređaji',
  'settings.texts.group.distributors': 'Distributeri',
  'settings.texts.group.subDistributors': 'Pod-distributeri',
  'settings.texts.group.tickets': 'Tiketi',
  'settings.texts.group.licences': 'Licence',
  'settings.texts.group.projects': 'Projekti',
  'settings.texts.group.projectDetail': 'Detalj projekta',
  'settings.texts.group.workOrders': 'Radni nalozi',
  'settings.texts.group.clients': 'Korisnici',
  'settings.texts.group.sales': 'Prodaja',
  'settings.texts.group.leave': 'Odsustva',
  'settings.texts.group.soldDevices': 'Prodati uređaji',
  'settings.texts.group.forms': 'Forms',
  'settings.texts.group.tables': 'Tables',

  // Settings — index & sekcije
  'settings.description': 'Izaberite sekciju ispod.',
  'settings.back': '← Settings',
  'settings.section.branding': 'Branding / White-label',
  'settings.section.email': 'Slanje mailova',
  'settings.section.users': 'Users & Roles',
  'settings.section.roles': 'Role i permisije',
  'settings.section.leave': 'Odsustva',
  'settings.section.todoTeams': 'TO DO timovi',
  'settings.section.accountantTodos': 'TO DO — podrazumevano vreme',
  'settings.section.tickets': 'Ticket Settings',
  'settings.section.tags': 'Tag Management',
  'settings.section.notifications': 'Email & Notifications',
  'settings.section.texts': 'Text Management',
  'settings.section.export': 'Data Export',
  'settings.section.security': 'Security',
  'settings.section.audit': 'Audit Log',

  // Settings — Role i permisije
  'settings.roles.title': 'Role i permisije',
  'settings.roles.description':
    'Globalni šabloni — View = vidljivost u meniju i čitanje; Edit = izmene i akcije. SUPER_ADMIN uvek ima pun pristup.',
  'settings.roles.rolesHeading': 'Uloge',
  'settings.roles.btn.new': '+ Nova',
  'settings.roles.slug.placeholder': 'SLUG npr. OFFICE_MGR',
  'settings.roles.name.placeholder': 'Naziv uloge',
  'settings.roles.btn.create': 'Kreiraj',
  'settings.roles.loading': 'Učitavanje…',
  'settings.roles.badge.system': 'sistemska',
  'settings.roles.userCount': 'korisnika',
  'settings.roles.selectRole': 'Izaberite ulogu.',
  'settings.roles.matrixLoading': 'Učitavanje matrice…',
  'settings.roles.readOnly':
    '{name} ima puna prava i ne konfiguriše se kroz matricu.',
  'settings.roles.assignUsers': 'Dodeli korisnicima →',
  'settings.roles.btn.delete': 'Obriši ulogu',
  'settings.roles.th.module': 'Modul',
  'settings.roles.th.view': 'View',
  'settings.roles.th.edit': 'Edit',
  'settings.roles.btn.save': 'Sačuvaj permisije',
  'settings.roles.btn.saving': 'Čuvanje…',
  'settings.roles.toast.saved': 'Permisije sačuvane.',
  'settings.roles.toast.saveError': 'Greška pri čuvanju permisija.',
  'settings.roles.toast.created': 'Uloga kreirana.',
  'settings.roles.toast.createError': 'Greška pri kreiranju uloge.',
  'settings.roles.toast.deleted': 'Uloga obrisana.',
  'settings.roles.toast.deleteError':
    'Uloga se ne može obrisati (sistemska ili dodeljena korisnicima).',

  // Settings — Users
  'settings.users.title': 'Users & Roles',
  'settings.users.description': 'Kreirajte i upravljajte korisnicima; reset lozinke.',
  'settings.users.btn.create': 'Create user',
  'settings.users.th.email': 'Email',
  'settings.users.th.name': 'Display name',
  'settings.users.th.role': 'Role',
  'settings.users.th.active': 'Active',
  'settings.users.th.actions': 'Actions',
  'settings.users.btn.edit': 'Edit',
  'settings.users.btn.resetPassword': 'Reset password',
  'settings.users.modal.create': 'Create user',
  'settings.users.modal.edit': 'Edit user',
  'settings.users.modal.resetPassword': 'Reset password',
  'settings.users.form.email': 'Email *',
  'settings.users.form.displayName': 'Display name',
  'settings.users.form.password': 'Password * (min 8)',
  'settings.users.form.role': 'Role',
  'settings.users.form.active': 'Active',
  'settings.users.btn.creating': 'Creating…',
  'settings.users.btn.createConfirm': 'Create',
  'settings.users.editing': 'Editing {email}',
  'settings.users.btn.save': 'Save',
  'settings.users.th.licenceAlerts': 'Licence alerts',
  'settings.users.active.yes': 'Yes',
  'settings.users.active.no': 'No',
  'settings.users.loading': 'Loading…',

  // Settings — TO DO računovođe
  'settings.accountantTodos.title': 'TO DO — podrazumevano vreme slanja',
  'settings.accountantTodos.description':
    'Podrazumevano vreme za timove koji nemaju sopstveno. Email digest se šalje po timovima — podesi članove i primaoce u TO DO timovi.',
  'settings.accountantTodos.form.time': 'Vreme slanja (Europe/Belgrade)',
  'settings.accountantTodos.form.recipients': 'Dodatni primaoci emaila',
  'settings.accountantTodos.form.recipients.placeholder':
    'email@firma.rs, jedan po redu ili zarezom',
  'settings.accountantTodos.btn.save': 'Sačuvaj',
  'settings.accountantTodos.btn.saving': 'Čuvanje…',
  'settings.accountantTodos.toast.saved': 'Podešavanja sačuvana.',
  'settings.accountantTodos.toast.error': 'Greška pri čuvanju podešavanja.',

  // Settings — TO DO timovi
  'settings.todoTeams.title': 'TO DO timovi',
  'settings.todoTeams.description':
    'Kreirajte timove, dodajte članove (jedna osoba može biti u više timova) i posebne email primaoce. Tab „Tim“ na TO DO stranici prikazuje taskove kolega iz zajedničkih timova.',
  'settings.todoTeams.btn.create': 'Novi tim',
  'settings.todoTeams.empty': 'Nema timova. Kreirajte prvi tim.',
  'settings.todoTeams.th.name': 'Naziv',
  'settings.todoTeams.th.members': 'Članovi',
  'settings.todoTeams.th.emails': 'Dodatni emailovi',
  'settings.todoTeams.th.time': 'Vreme slanja',
  'settings.todoTeams.timeDefault': 'podrazumevano',
  'settings.todoTeams.inactive': 'neaktivan',
  'settings.todoTeams.deleteConfirm': 'Obrisati ovaj tim?',
  'settings.todoTeams.modal.create': 'Novi TO DO tim',
  'settings.todoTeams.modal.edit': 'Izmeni TO DO tim',
  'settings.todoTeams.form.name': 'Naziv tima',
  'settings.todoTeams.form.members': 'Članovi tima',
  'settings.todoTeams.form.membersHint':
    'Korisnici vide aktivne taskove kolega sa kojima dele bar jedan tim.',
  'settings.todoTeams.form.emails': 'Dodatni primaoci email digesta',
  'settings.todoTeams.form.emails.placeholder': 'email@firma.rs, jedan po redu ili zarezom',
  'settings.todoTeams.form.time': 'Vreme slanja (Europe/Belgrade)',
  'settings.todoTeams.form.timeHint': 'Prazno = koristi podrazumevano iz TO DO podešavanja.',
  'settings.todoTeams.form.active': 'Aktivan tim',
  'settings.todoTeams.toast.saved': 'Tim sačuvan.',
  'settings.todoTeams.toast.saveError': 'Greška pri čuvanju tima.',
  'settings.todoTeams.toast.deleted': 'Tim obrisan.',
  'settings.todoTeams.toast.deleteError': 'Tim se ne može obrisati.',

  // Navigacija
  'nav.group.home': 'Početna',
  'nav.group.service': 'Servis',
  'nav.group.clients': 'Klijenti',
  'nav.group.devices': 'Uređaji',
  'nav.group.people': 'Organizacija',
  'nav.group.reports': 'Izveštaji',
  'nav.group.data': 'Podaci',
  'nav.dashboard': 'Početna strana',
  'nav.todo': 'Lista obaveza',
  'nav.tickets': 'Tiketi',
  'nav.sales': 'Prodaja',
  'nav.clients': 'Korisnici',
  'nav.devices': 'Uređaji',
  'nav.distributors': 'Distributeri',
  'nav.subDistributors': 'Pod-distributeri',
  'nav.licences': 'Licence',
  'nav.projects': 'Evidencija rada po projektima',
  'nav.leave': 'Odsustva',
  'nav.travelOrders': 'Putni nalozi',
  'nav.soldDevices': 'Prodati uređaji',
  'nav.reports': 'Izveštaji',
  'nav.reports.overview': 'Pregled',
  'nav.reports.tickets': 'Tiketi',
  'nav.reports.licences': 'Licence',
  'nav.reports.devices': 'Uređaji',
  'nav.reports.tables': 'Tabele',
  'nav.reports.generator': 'Generator',
  'nav.reports.alerts': 'Upozorenja',
  'nav.forms': 'Forme',
  'nav.tables': 'Tabele',

  // Okvir aplikacije
  'shell.settings': 'Podešavanja',
  'shell.platform': 'Platforma',
  'shell.logout': 'Odjava',
  'shell.quickCall': 'Quick Call',
  'shell.outgoingCall': 'Outgoing Call',
  'shell.impersonating':
    'Impersonating tenant – actions affect tenant data.',
  'shell.stopImpersonation': 'Stop impersonation',
  'shell.leaveBanner':
    'Imate neiskorišćen godišnji odmor{days} — iskoristite do 30.06.',
  'shell.leaveBanner.open': 'Otvori odsustva',
  'shell.leaveBanner.dismiss': 'Zatvori',
  'shell.account.photo': 'Slika profila',
  'shell.account.photoHint': 'PNG ili JPG, najviše 2 MB',
  'shell.account.annual': 'Preostali godišnji odmor',
  'shell.account.annualDays': '{days} dana',
  'shell.account.annualLoading': 'Učitavanje salda…',
  'shell.account.requestLeave': 'Zatraži slobodne dane',
  'shell.account.openLeave': 'Odsustva',
  'shell.account.changePassword': 'Promena lozinke',
  'account.password.title': 'Promena lozinke',
  'account.password.description': 'Unesite trenutnu lozinku, pa novu lozinku dva puta.',
  'account.password.current': 'Trenutna lozinka',
  'account.password.new': 'Nova lozinka',
  'account.password.confirm': 'Potvrdite novu lozinku',
  'account.password.submit': 'Sačuvaj lozinku',
  'account.password.saving': 'Čuvanje…',
  'account.password.mismatch': 'Nova lozinka i potvrda se ne poklapaju.',
  'account.password.short': 'Nova lozinka mora imati najmanje 8 karaktera.',
  'account.password.saved': 'Lozinka je promenjena.',
  'account.password.failed': 'Lozinka nije promenjena.',

  // Opšte
  'common.back': '← Nazad',
  'common.backSettings': '← Settings',
  'common.loading': 'Učitavanje…',
  'common.save': 'Sačuvaj',
  'common.saving': 'Čuvanje…',
  'common.cancel': 'Otkaži',
  'common.delete': 'Obriši',
  'common.edit': 'Edit',
  'common.actions': 'Akcije',
  'common.viewAll': 'View all →',
  'common.yes': 'Da',
  'common.no': 'Ne',
  'common.close': 'Zatvori',

  // Dashboard
  'dashboard.title': 'Dashboard',
  'dashboard.description.accountant': 'Pregled obaveza i odsustava.',
  'dashboard.description.default': 'Quick overview of your tickets.',
  'dashboard.todo.openAll': 'Otvori sve →',
  'dashboard.todo.mineTasks': 'Moji taskovi',
  'dashboard.todo.widget.title': 'TO DO',
  'dashboard.todo.mineToday': 'Moji danas',
  'dashboard.todo.teamToday': 'Tim danas',
  'dashboard.todo.empty.mine': 'Nema aktivnih taskova.',
  'dashboard.todo.empty.team': 'Nema taskova tima.',
  'dashboard.widget.myOpen': 'My Open tickets',
  'dashboard.widget.unassigned': 'Unassigned Open',
  'dashboard.widget.recent': 'Recent tickets',
  'dashboard.widget.devices': 'Devices overview',
  'dashboard.widget.devices.sub': 'Active devices',
  'dashboard.widget.licences': 'Licences overview',
  'dashboard.widget.licences.sub': 'Active licences',
  'dashboard.widget.leave': 'Odsustva',
  'dashboard.widget.absentToday': 'Danas odsutni',
  'dashboard.empty.myOpen': 'No open tickets assigned to you.',
  'dashboard.empty.unassigned': 'No unassigned open tickets.',

  // TO DO
  'todo.title': 'TO DO',
  'todo.description':
    'Interne računovodstvene obaveze — unos u tabeli, podsetnici na email.',
  'todo.tab.mine': 'Moji',
  'todo.tab.team': 'Tim',
  'todo.filter.team': 'Tim',
  'todo.filter.allTeams': 'Svi moji timovi',
  'todo.th.teams': 'Timovi',
  'todo.tab.completed': 'Završeni',
  'todo.th.user': 'Korisnik',
  'todo.th.task': 'Task',
  'todo.th.due': 'Rok',
  'todo.th.reminder': 'Podsetnik',
  'todo.th.status': 'Status',
  'todo.th.completedAt': 'Završeno',
  'todo.th.actions': 'Akcije',
  'todo.new.placeholder': 'Novi task — kucaj i klikni van reda (Ctrl+Enter)',
  'todo.empty': 'Nema taskova.',
  'todo.delete.confirm': 'Obrisati ovaj task?',
  'todo.btn.today': 'Danas',
  'todo.btn.edit': 'Izmeni',
  'todo.btn.close': 'Zatvori',
  'todo.btn.delete': 'Obriši',
  'todo.status.active': 'Aktivan',
  'todo.status.completed': 'Završen',
  'todo.reminder.on': 'Da',
  'todo.reminder.off': 'Ne',
  'todo.toast.createError': 'Greška pri kreiranju taska.',
  'todo.toast.saveError': 'Greška pri čuvanju taska.',
  'todo.toast.deleteError': 'Greška pri brisanju taska.',

  // Forms
  'forms.title': 'Forms',
  'forms.description': 'Create forms, add questions, publish and view submissions.',
  'forms.btn.create': 'Create form',
  'forms.loading': 'Loading…',
  'forms.th.title': 'Title',
  'forms.th.status': 'Status',
  'forms.th.updated': 'Updated',
  'forms.th.actions': 'Actions',
  'forms.action.builder': 'Builder',
  'forms.action.responses': 'Responses',
  'forms.action.publish': 'Publish',
  'forms.action.unpublish': 'Unpublish',
  'forms.action.clone': 'Clone',
  'forms.action.sendLink': 'Pošalji na mail',
  'forms.empty': 'No forms yet.',
  'forms.modal.create': 'Create form',
  'forms.form.title': 'Title *',
  'forms.form.description': 'Description',
  'forms.btn.cancel': 'Cancel',
  'forms.btn.createConfirm': 'Create',
  'forms.modal.sendLink': 'Pošalji na mail',
  'forms.modal.sendLink.title': 'Pošalji formu na mail: {title}',
  'forms.sendLink.hint': 'Primaoc dobija link za popunjavanje forme.',
  'forms.sendLink.email': 'Email primaoca *',
  'forms.sendLink.email.placeholder': 'npr. korisnik@example.com',
  'forms.sendLink.message': 'Poruka (opciono)',
  'forms.sendLink.message.placeholder': 'Dodatni tekst u mailu...',
  'forms.sendLink.btn.send': 'Pošalji',

  // Tables
  'tables.title': 'Tables',
  'tables.description': 'Choose a form to view pivot table (questions × submissions).',
  'tables.loading': 'Loading…',
  'tables.empty': 'No forms. Create one under Forms.',

  // Reports — podstranice
  'reports.description': 'Izveštaji i analitika.',
  'reports.overview.title': 'Pregled',
  'reports.tickets.title': 'Tiketi',
  'reports.devices.title': 'Uređaji',
  'reports.tables.title': 'Tabele',
  'reports.licences.title': 'Licence',
  'reports.alerts.title': 'Alerti',
  'reports.generator.description': 'AI generator izveštaja na osnovu podataka iz CRM-a.',
  'reports.overview.card.companies': 'Companies',
  'reports.overview.card.companies.sub': 'Total clients',
  'reports.overview.card.devices': 'Active devices',
  'reports.overview.card.licences': 'Active licences',
  'reports.overview.card.tickets': 'Total tickets',
  'reports.overview.card.tickets.sub': 'All statuses',
  'reports.overview.ticketsByStatus': 'Tickets by status',
  'reports.overview.ticketsByType': 'Tickets by type',
  'reports.overview.licencesExpiring': 'Licences expiring soon',
  'reports.overview.status.open': 'Open',
  'reports.overview.status.inProgress': 'In progress',
  'reports.overview.status.done': 'Done',
  'reports.overview.type.call': 'Call',
  'reports.overview.type.support': 'Support',
  'reports.overview.type.sales': 'Sales',
  'reports.overview.type.field': 'Field',
  'reports.overview.type.other': 'Other',

  // Leave — prošireno
  'leave.description': 'Zahtevi za odsustvo — pregled kompanije ili lični.',
  'leave.status.approved': 'Odobreno',
  'leave.status.pending': 'Na čekanju',
  'leave.type.paidAbsence': 'Plaćeno odsustvo',
  'leave.type.personalDay': 'Slobodan dan',
  'leave.loading': 'Učitavanje…',
  'leave.empty': 'Nema zahteva za izabrani period.',

  // Clients — detalj
  'clients.detail.back': '← Nazad na korisnike',
  'clients.detail.edit': 'Izmeni korisnika',
  'clients.detail.view': 'Pregled korisnika',
  'clients.detail.devices': 'Uređaji',
  'clients.detail.users': 'Korisnici portala',
  'clients.detail.addons': 'Dodatci',
  'clients.detail.btn.assignDevice': 'Dodeli uređaj',
  'clients.detail.btn.addUser': 'Dodaj korisnika portala',
  'clients.detail.th.actions': 'Akcije',

  'soldDevices.title': 'Prodati uređaji',
  'soldDevices.description': 'Unos prodatih uređaja sa strane tehničkog tima.',
  'soldDevices.form.serial': 'SN',
  'soldDevices.form.name': 'Naziv (opciono)',
  'soldDevices.form.licence': 'Licenca',
  'soldDevices.form.months': 'Trajanje (meseci)',
  'soldDevices.form.description': 'Opis (opciono)',
  'soldDevices.btn.submit': 'Sačuvaj',
  'soldDevices.btn.saving': 'Čuvam…',
  'soldDevices.saved': 'Uređaj je sačuvan.',
  'soldDevices.list.title': 'Evidentirani uređaji',
  'soldDevices.loading': 'Učitavanje…',
  'soldDevices.error': 'Učitavanje nije uspelo.',
  'soldDevices.empty': 'Još nema unetih uređaja.',
  'soldDevices.th.serial': 'SN',
  'soldDevices.th.name': 'Naziv',
  'soldDevices.th.licence': 'Licenca',
  'soldDevices.th.months': 'Meseci',
  'soldDevices.th.description': 'Opis',
  'soldDevices.th.enteredBy': 'Uneo',
  'soldDevices.th.date': 'Datum',
};

